export const MUSCLE_KEYS = [
  'neck',
  'traps',
  'shoulders',
  'chest',
  'biceps',
  'triceps',
  'forearms',
  'abs',
  'obliques',
  'back',
  'lower_back',
  'glutes',
  'adductors',
  'quads',
  'hamstrings',
  'calves',
  'tibialis',
]

export const BODY_PART_KEYS = ['head', 'hair', 'hands', 'knees', 'ankles', 'feet']

export const MUSCLE_LABELS = {
  neck: 'Neck',
  traps: 'Traps',
  shoulders: 'Shoulders',
  chest: 'Chest',
  biceps: 'Biceps',
  triceps: 'Triceps',
  forearms: 'Forearms',
  abs: 'Abs',
  obliques: 'Obliques',
  back: 'Back',
  lower_back: 'Lower back',
  glutes: 'Glutes',
  adductors: 'Adductors',
  quads: 'Quads',
  hamstrings: 'Hamstrings',
  calves: 'Calves',
  tibialis: 'Tibialis',
  head: 'Head',
  hair: 'Hair',
  hands: 'Hands',
  knees: 'Knees',
  ankles: 'Ankles',
  feet: 'Feet',
}
